# Generated by Django 5.0.2 on 2024-03-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acronym_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
