# Generated by Django 5.0.2 on 2024-03-16 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_shortened', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveurlshortened',
            name='account_user',
        ),
        migrations.AddField(
            model_name='saveurlshortened',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saveurlshortened',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saveurlshortened',
            name='original_url',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='saveurlshortened',
            name='short_url',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
