# Generated by Django 5.0.2 on 2024-03-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_shortened', '0003_alter_saveurlshortened_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveurlshortened',
            options={'verbose_name_plural': 'Url Shorts'},
        ),
        migrations.AlterModelTable(
            name='saveurlshortened',
            table='urls_shorts',
        ),
    ]
