# Generated by Django 5.0.2 on 2024-03-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_shortened', '0005_alter_saveurlshortened_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveurlshortened',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
