# Generated by Django 5.0.2 on 2024-03-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_shortened', '0006_alter_saveurlshortened_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveurlshortened',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
