# Generated by Django 5.0.2 on 2024-04-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlanalytics',
            name='id_short_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
