# Generated by Django 5.0.2 on 2024-04-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_qranalytics_alter_urlanalytics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlanalytics',
            name='creator',
            field=models.CharField(default='', max_length=200),
        ),
    ]
