# Generated by Django 5.0.2 on 2024-04-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_urlanalytics_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='qranalytics',
            name='creator',
            field=models.CharField(default='', max_length=200),
        ),
    ]
