# Generated by Django 5.0.2 on 2024-04-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_qranalytics_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qranalytics',
            old_name='mobile_system',
            new_name='system',
        ),
        migrations.RenameField(
            model_name='urlanalytics',
            old_name='mobile_system',
            new_name='system',
        ),
    ]
