# Generated by Django 5.0.2 on 2024-03-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveurlshortened',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
