# Generated by Django 5.0.2 on 2024-03-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_link', '0002_saveurlshortened_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveurlshortened',
            name='short_url',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
