# Generated by Django 5.0.2 on 2024-03-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_link', '0003_alter_saveurlshortened_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveurlshortened',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
