# Generated by Django 5.0.2 on 2024-03-24 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_link', '0005_saveurlshortened_icon_saveurlshortened_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveurlshortened',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
