# Generated by Django 5.0.2 on 2024-03-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_link', '0008_alter_saveurlshortened_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveurlshortened',
            name='icon',
            field=models.CharField(default='../media/default/icon_broken.webp', max_length=400),
        ),
    ]
