# Generated by Django 5.0.2 on 2024-04-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_link', '0009_alter_saveurlshortened_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveurlshortened',
            name='type_app',
            field=models.CharField(default='', max_length=100),
        ),
    ]
