# Generated by Django 5.0.2 on 2024-05-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_link', '0010_saveurlshortened_type_app'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveUrlShortened',
            new_name='ModelSaveUrlShortened',
        ),
    ]
