# Generated by Django 5.0.2 on 2024-03-20 01:46

import qr_codes_link.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('original_url', models.CharField(default='', max_length=500)),
                ('url_short', models.CharField(default='', max_length=300, unique=True)),
                ('qr_image', models.ImageField(upload_to=qr_codes_link.models.QRGenerator.image_upload_to)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'QR Codes Images',
                'db_table': 'qr_code_images',
            },
        ),
    ]
