# Generated by Django 5.0.2 on 2024-03-31 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes_link', '0002_rename_url_short_qrgenerator_short_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrgenerator',
            options={'verbose_name_plural': 'QR Codes Links'},
        ),
        migrations.AlterModelTable(
            name='qrgenerator',
            table='qr_code_links',
        ),
    ]
