# Generated by Django 5.0.2 on 2024-03-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes_link', '0004_alter_qrgenerator_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrgenerator',
            name='short_url',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='qrgenerator',
            name='title',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
    ]
