# Generated by Django 5.0.2 on 2024-03-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes_link', '0005_alter_qrgenerator_short_url_alter_qrgenerator_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrgenerator',
            name='original_url',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='qrgenerator',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
