# Generated by Django 5.0.2 on 2024-04-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes_link', '0006_alter_qrgenerator_original_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrgenerator',
            name='color_qr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
