# Generated by Django 5.0.2 on 2024-04-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes_link', '0008_qrgenerator_bg_color_qr_qrgenerator_border_qr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrgenerator',
            name='zone_color_qr',
        ),
        migrations.AddField(
            model_name='qrgenerator',
            name='border_color_qr',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=200),
        ),
        migrations.AlterField(
            model_name='qrgenerator',
            name='bg_color_qr',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=200),
        ),
        migrations.AlterField(
            model_name='qrgenerator',
            name='color_qr',
            field=models.CharField(blank=True, default='#000000', max_length=200),
        ),
    ]
