# Generated by Django 5.0.2 on 2024-04-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes_link', '0011_alter_qrgenerator_bg_color_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrgenerator',
            name='short_url',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
