# Generated by Django 5.0.2 on 2024-04-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes_link', '0012_alter_qrgenerator_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrgenerator',
            old_name='clicks',
            new_name='scans',
        ),
    ]
