# Generated by Django 5.0.2 on 2024-04-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes_link', '0013_rename_clicks_qrgenerator_scans'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrgenerator',
            name='type_app',
            field=models.CharField(default='', max_length=100),
        ),
    ]
