# Generated by Django 5.0.2 on 2024-05-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes_link', '0014_qrgenerator_type_app'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QRGenerator',
            new_name='ModelQR',
        ),
    ]
